

server:
  port: 9001


eureka:
  instance:
    hostname: eureka9001.com

  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false
    #eureka.client.serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单节点配置
      defaultZone: http://eureka9002.com:9002/eureka/ #集群配置

