

server:
  port: 10001

spring:
  application:
    name: bbs-sms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/common-sms?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:  #客户端服务注册到eureka中
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/ #,http://eureka9002.com:9002/eureka/


#阿里云短信配置
aliyun:
  sms:
   accesskey: LTAIyAJHbscmRyZV
   secretKey: Vw6hkwelizbRwZFuonHNThE5xyqG93
   phoneMax: 5
   sendMessageTime: 60000  #同一个号码两次短信最小间隔时间一分钟
   codeValidTime: 300000 #短信有效时间5分钟