

server:
  port: 8002

spring:
  application:
    name: bbs-forum     #服务名字
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs-forum?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource  #当前数据源操作类型
    hikari:   #hikari连接池配置
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 3000
      pool-name: DatebookHikariCp
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:  #客户端服务注册到eureka中
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: forum_service_8002  #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP信息


#服务信息(用于显示eureka点击服务后的提示说明)
info:
  app.name: bbs
  company.name: www.bbs.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
